prefix = "."
dataset = "apnews"
corpus = "line.toml"
index = "idx"
query-judgements = "qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = [{type = "icu-tokenizer", suppress-tags = true}, {type = "lowercase"}]

[ranker]
method = "bm25"
k1 = 1.2
b = 0.75
k3 = 500
